#placeholder
FROM nginx:latest
LABEL org.opencontainers.image.source = "https://github.com/HighLord-Syagrius/pi_docker"

COPY ./overrides/index.html /usr/share/nginx/html/index.html
COPY ./overrides/favicon.ico /usr/share/nginx/html/favicon.ico
COPY ./overrides/favicon.ico /favicon.ico
